#!/bin/sh
currentPath=`pwd`
cd ../../lib
libPath=`pwd`
cd $currentPath
jar xf ../../lib/dtree.zip
java -classpath $CLASSPATH:$libPath/xstream-1.3.1.jar:$libPath/c45.jar ml.demo.C45Spring "iris-hibernation.xml" >iris-spring.html
